services:
  vascu-track:
    image: nginx:alpine
    container_name: vascu-track-services
    volumes:
      - ./nginx/vascu_track.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/home/vascuTrack/neurovascai/dist
    ports:
      - "8080:80"
    restart: unless-stopped
